add

diff --git a/mytools/tide b/mytools/tide
--- a/mytools/tide
+++ b/mytools/tide
@@ -26,14 +26,15 @@ OPTIONS:
     -t, --type {1,2,3}      Type of window. Choose {1,2,3}.
                             type1 means 2+3 window, type2 means 2x2 window, type3 means 1+1 window [default: 1]
     -x, --top-off           Do not put on top on the right edge [default: not set]
-    -p, --path [PATH]       Start from specifieed path [default: default set path]
+    -c, --cmd [command]     Command to run after log into tmux
 '
 
 # default setting
 tmux_window_name="home"
 window_type="1"
 top_off=0
-start_path=""
+# start_path=""
+cmd=""
 
 # tmux check
 if [ ! -x $(which tmux) ]; then
@@ -80,12 +81,20 @@ do
         -x | --top-off)
             top_off=1
             ;;
-        -p | --path)
+        # -p | --path)
+        #     if [ -z "$2" ]; then
+        #         echo "[ERROR] path is necessary, if -p/--path option is present" >&2
+        #         exit 1
+        #     fi
+        #     start_path="$2"
+        #     shift
+        #     ;;
+        -c | --cmd)
             if [ -z "$2" ]; then
-                echo "[ERROR] path is necessary, if -p/--path option is present" >&2
+                echo "[ERROR] command is necessary, if -c/--cmd option is present" >&2
                 exit 1
             fi
-            start_path="$2"
+            cmd="$2"
             shift
             ;;
         --)
@@ -118,13 +127,13 @@ if [ $window_type == "1" ]; then
     [ $top_off -eq 0 ] && tmux send-keys -t 4 "top" C-m
     tmux select-pane -t 0
 
-    if [ -n "$start_path" ]; then
+    if [ -n "$cmd" ]; then
         for i in {0..4};
         do
             if [ $i -eq 4 ] && [ $top_off -eq 0 ]; then
                 break
             fi
-            tmux send-keys -t $i "cd $start_path" C-m
+            tmux send-keys -t $i "$cmd" C-m
         done
     fi
 fi
@@ -138,13 +147,13 @@ if [ $window_type == "2" ]; then
     [ $top_off -eq 0 ] && tmux send-keys -t 3 "top" C-m
     tmux select-pane -t 0
 
-    if [ -n "$start_path" ]; then
+    if [ -n "$cmd" ]; then
         for i in {0..3};
         do
             if [ $i -eq 3 ] && [ $top_off -eq 0 ]; then
                 break
             fi
-            tmux send-keys -t $i "cd $start_path" C-m
+            tmux send-keys -t $i "$cmd" C-m
         done
     fi
 fi
@@ -152,10 +161,10 @@ fi
 if [ $window_type == "3" ]; then
     tmux split-window -h
     tmux select-pane -t 0
-    if [ -n "$start_path" ]; then
+    if [ -n "$cmd" ]; then
         for i in {0..1};
         do
-            tmux send-keys -t $i "cd $start_path" C-m
+            tmux send-keys -t $i "$cmd" C-m
         done
     fi
 fi
